#!/usr/bin/env python3
"""Train a real SchNetPack 2 model on QM training data generated by
`cargo run -p gromos-md --example generate_qm_training_data`, and export it
to TorchScript for `nonbonded/schnet.rs`'s `SchNetInteraction` to load.

This is the "train" step of the QM/MM -> ML/MM pipeline (PLAN.md P2.9):
1. QM/MM (real `XtbInteraction`, `Embedding::None`) generates training data
   — see the example's own docs for why the target is deliberately the
   *isolated* QM-zone energy, not an electrostatically-embedded one.
2. This script trains on that data.
3. `crates/gromos-md/tests/qm_vs_ml_comparison.rs` runs the trained model as
   ML/MM and compares it against real QM/MM on held-out configurations.

Uses the *same* model architecture `export_toy_schnet.py` exports (imported
directly, not duplicated) — `SchNet` representation + `Atomwise` energy head
+ `Forces(calc_forces=True)` (populates the autograd derivative that gives
forces), so the trained model has the identical Dict[str, Tensor] input/
output contract `schnet.rs` already implements against. Capacity is bumped
from the toy defaults since this one actually needs to fit real data — still
small enough for a 3-atom system to train in seconds on CPU.

Not a hand-rolled training loop reimplementing SchNetPack internals — just a
direct loop against the model's own forward pass, simpler to read and debug
at this scale than SchNetPack's config-driven `Task`/`Trainer`/hydra
machinery.

Run in the same venv `--features ml` needs (see `schnet.rs` module docs):

    source /tmp/torch_venv/bin/activate
    python3 scripts/train_qmmm_schnet.py [dataset_path] [output_path]
"""

import sys
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent))
from export_toy_schnet import build_model  # noqa: E402


def load_dataset(path: Path):
    """Parse `generate_qm_training_data.rs`'s output format: header line
    `n_atoms Z1 Z2 ... Zn`, then one line per frame:
    `energy px1 py1 pz1 fx1 fy1 fz1 ...` (GROMOS-native units: nm, kJ/mol,
    kJ/mol/nm — no conversion needed, matching what `schnet.rs` expects).
    """
    with open(path) as f:
        header = f.readline().split()
        n_atoms = int(header[0])
        atomic_numbers = [int(z) for z in header[1 : 1 + n_atoms]]

        energies = []
        positions = []
        forces = []
        for line in f:
            vals = [float(x) for x in line.split()]
            energies.append(vals[0])
            rest = vals[1:]
            pos = [rest[i * 6 : i * 6 + 3] for i in range(n_atoms)]
            frc = [rest[i * 6 + 3 : i * 6 + 6] for i in range(n_atoms)]
            positions.append(pos)
            forces.append(frc)

    return (
        atomic_numbers,
        torch.tensor(energies, dtype=torch.float32),
        torch.tensor(positions, dtype=torch.float32),
        torch.tensor(forces, dtype=torch.float32),
    )


def fully_connected_edges(n_atoms: int):
    """Both directions, every pair — matches `schnet.rs`'s own edge convention.
    Vacuum system (no PBC), so every `_offsets` entry is zero."""
    idx_i, idx_j = [], []
    for i in range(n_atoms):
        for j in range(n_atoms):
            if i != j:
                idx_i.append(i)
                idx_j.append(j)
    idx_i = torch.tensor(idx_i, dtype=torch.int64)
    idx_j = torch.tensor(idx_j, dtype=torch.int64)
    offsets = torch.zeros((len(idx_i), 3), dtype=torch.float32)
    return idx_i, idx_j, offsets


def model_inputs(positions, atomic_numbers, idx_i, idx_j, offsets):
    n_atoms = positions.shape[0]
    return {
        "_positions": positions.clone().requires_grad_(True),
        "_atomic_numbers": torch.tensor(atomic_numbers, dtype=torch.int64),
        "_idx_i": idx_i,
        "_idx_j": idx_j,
        "_offsets": offsets,
        "_n_atoms": torch.tensor([n_atoms], dtype=torch.int64),
        "_idx_m": torch.zeros(n_atoms, dtype=torch.int64),
    }


def main() -> None:
    dataset_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/qm_water_training_data.txt")
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("/tmp/trained_water_schnet.pt")

    atomic_numbers, energies, positions, forces = load_dataset(dataset_path)
    n_frames, n_atoms, _ = positions.shape
    print(f"loaded {n_frames} frames, {n_atoms} atoms ({atomic_numbers}) from {dataset_path}")

    idx_i, idx_j, offsets = fully_connected_edges(n_atoms)

    torch.manual_seed(0)
    model = build_model(cutoff=1.0, n_atom_basis=32, n_interactions=2)
    model.train()

    n_val = max(1, n_frames // 10)
    perm = torch.randperm(n_frames)
    val_idx, train_idx = perm[:n_val], perm[n_val:]

    optimizer = torch.optim.Adam(model.parameters(), lr=3e-3)
    # Forces carry most of the training signal at this system size (many more force components
    # than one energy value per frame) but have larger raw magnitude than energy differences
    # between nearby conformations, so the force term is down-weighted rather than the more
    # common reverse convention.
    force_weight = 0.01
    n_epochs = 400

    def run_epoch(indices, train: bool):
        total_loss = 0.0
        for idx in indices.tolist():
            inputs = model_inputs(positions[idx], atomic_numbers, idx_i, idx_j, offsets)
            out = model(inputs)
            e_loss = torch.nn.functional.mse_loss(out["energy"], energies[idx].unsqueeze(0))
            f_loss = torch.nn.functional.mse_loss(out["forces"], forces[idx])
            loss = e_loss + force_weight * f_loss
            if train:
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
            total_loss += loss.item()
        return total_loss / len(indices)

    for epoch in range(n_epochs):
        train_loss = run_epoch(train_idx, train=True)
        if epoch % 50 == 0 or epoch == n_epochs - 1:
            model.eval()
            with torch.enable_grad():  # Forces module needs grad even in eval mode
                val_loss = run_epoch(val_idx, train=False)
            model.train()
            print(f"epoch {epoch:4d}: train_loss={train_loss:.6f} val_loss={val_loss:.6f}")

    model.eval()
    scripted = torch.jit.script(model)
    scripted.save(str(out_path))
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
