"""Type stubs for the gromos native extension module (gromos.abi3.so)."""

from __future__ import annotations

import numpy as np
import numpy.typing as npt

# =============================================================================
# Vec3
# =============================================================================

class Vec3:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def length(self) -> float: ...
    def dot(self, other: Vec3) -> float: ...
    def cross(self, other: Vec3) -> Vec3: ...
    def normalize(self) -> Vec3: ...
    def __repr__(self) -> str: ...
    def __add__(self, other: Vec3) -> Vec3: ...
    def __sub__(self, other: Vec3) -> Vec3: ...
    def __mul__(self, scalar: float) -> Vec3: ...

# =============================================================================
# Energy
# =============================================================================

class Energy:
    def __init__(self) -> None: ...
    @property
    def total(self) -> float: ...
    @property
    def kinetic(self) -> float: ...
    @property
    def potential(self) -> float: ...
    def __repr__(self) -> str: ...

# =============================================================================
# Frame
# =============================================================================

class Frame:
    def __init__(self, time: float, step: int) -> None: ...
    @property
    def time(self) -> float: ...
    @property
    def step(self) -> int: ...
    @property
    def n_atoms(self) -> int: ...
    def positions_array(self) -> npt.NDArray[np.float32]: ...
    def __repr__(self) -> str: ...

# =============================================================================
# Topology
# =============================================================================

class Topology:
    def __init__(self, topo_file: str) -> None: ...
    @property
    def n_atoms(self) -> int: ...
    @property
    def n_solute_atoms(self) -> int: ...
    @property
    def n_solvent_atoms(self) -> int: ...
    @property
    def masses(self) -> npt.NDArray[np.float64]: ...
    @property
    def charges(self) -> npt.NDArray[np.float64]: ...
    def solvate(self, nsm: int) -> None: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...

# =============================================================================
# Configuration
# =============================================================================

class Configuration:
    def __init__(self, conf_file: str) -> None: ...
    @property
    def n_atoms(self) -> int: ...
    @property
    def positions(self) -> npt.NDArray[np.float64]: ...
    @property
    def velocities(self) -> npt.NDArray[np.float64]: ...
    @property
    def box_dimensions(self) -> tuple[float, float, float]: ...
    def __repr__(self) -> str: ...

# =============================================================================
# InputParameters
# =============================================================================

class InputParameters:
    def __init__(self, input_file: str) -> None: ...
    @property
    def dt(self) -> float: ...
    @property
    def nstlim(self) -> int: ...
    @property
    def nsm(self) -> int: ...
    @property
    def cutoff(self) -> float: ...
    @property
    def rcutp(self) -> float: ...
    @property
    def temperature(self) -> float: ...
    @property
    def ntc(self) -> int: ...
    @property
    def ntb(self) -> int: ...
    @property
    def nsnb(self) -> int: ...
    @property
    def ntwx(self) -> int: ...
    @property
    def ntwe(self) -> int: ...
    def __repr__(self) -> str: ...

# =============================================================================
# Simulation
# =============================================================================

class Simulation:
    def __init__(
        self,
        arg1: str | Topology,
        arg2: str | Configuration,
        arg3: str | InputParameters,
    ) -> None: ...
    @staticmethod
    def from_files(
        topo_file: str, conf_file: str, input_file: str
    ) -> Simulation: ...
    @staticmethod
    def from_sequence(
        topo: Topology,
        conf: Configuration,
        params: InputParameters,
        sequence: AlgorithmSequence,
    ) -> Simulation: ...
    def step(self, n_steps: int) -> None: ...
    @property
    def time(self) -> float: ...
    @property
    def current_step(self) -> int: ...
    @property
    def dt(self) -> float: ...
    @property
    def n_atoms(self) -> int: ...
    @property
    def algorithm_names(self) -> list[str]: ...
    @property
    def positions(self) -> npt.NDArray[np.float64]: ...
    @property
    def velocities(self) -> npt.NDArray[np.float64]: ...
    @property
    def forces(self) -> npt.NDArray[np.float64]: ...
    @property
    def energies(self) -> Energy: ...
    @property
    def total_energy(self) -> float: ...
    @property
    def potential_energy(self) -> float: ...
    @property
    def kinetic_energy(self) -> float: ...
    @property
    def temperature(self) -> float: ...
    @property
    def n_solute_atoms(self) -> int: ...
    @property
    def n_solvent_atoms(self) -> int: ...
    def __repr__(self) -> str: ...

# =============================================================================
# Algorithm sequence API
# =============================================================================

class Forcefield:
    cutoff: float | None
    rcutp: float | None
    epsilon_rf: float | None
    kappa: float | None
    pairlist_update: int | None
    virial: str | None
    ntf_bond: bool | None
    ntf_angle: bool | None
    ntf_improper: bool | None
    ntf_dihedral: bool | None
    def __init__(
        self,
        cutoff: float | None = ...,
        rcutp: float | None = ...,
        epsilon_rf: float | None = ...,
        kappa: float | None = ...,
        pairlist_update: int | None = ...,
        virial: str | None = ...,
        ntf_bond: bool | None = ...,
        ntf_angle: bool | None = ...,
        ntf_improper: bool | None = ...,
        ntf_dihedral: bool | None = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...

class LeapFrogIntegrator:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

class LeapFrogVelocity:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

class LeapFrogPosition:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

class BerendsenThermostat:
    temperature: float
    tau: float
    def __init__(self, temperature: float = ..., tau: float = ...) -> None: ...
    def __repr__(self) -> str: ...

class BerendsenBarostat:
    pressure: float
    tau: float
    compressibility: float
    virial: str | None
    def __init__(
        self,
        pressure: float = ...,
        tau: float = ...,
        compressibility: float = ...,
        virial: str | None = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...

class ShakeConstraints:
    tolerance: float
    max_iterations: int
    mode: str
    def __init__(
        self,
        tolerance: float = ...,
        max_iterations: int = ...,
        mode: str = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...

class TemperatureCalculation:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

class PressureCalculation:
    virial: str
    def __init__(self, virial: str = ...) -> None: ...
    def __repr__(self) -> str: ...

class EnergyCalculation:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

class RemoveCOMMotion:
    initial: bool
    nscm: int
    def __init__(self, initial: bool = ..., nscm: int = ...) -> None: ...
    def __repr__(self) -> str: ...

class AlgorithmSequence:
    def __init__(self) -> None: ...
    def add(self, algorithm: object) -> None: ...
    def insert_after(self, after: str, algorithm: object) -> None: ...
    def insert_before(self, before: str, algorithm: object) -> None: ...
    def remove(self, name: str) -> None: ...
    def replace(self, name: str, algorithm: object) -> None: ...
    @property
    def names(self) -> list[str]: ...
    @staticmethod
    def nve(topo: Topology, params: InputParameters) -> AlgorithmSequence: ...
    @staticmethod
    def nvt(topo: Topology, params: InputParameters) -> AlgorithmSequence: ...
    @staticmethod
    def npt(topo: Topology, params: InputParameters) -> AlgorithmSequence: ...
    @staticmethod
    def from_parameters(
        topo: Topology, params: InputParameters
    ) -> AlgorithmSequence: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __repr__(self) -> str: ...

# =============================================================================
# Free functions
# =============================================================================

def rmsd(
    positions: npt.NDArray[np.float32],
    reference: npt.NDArray[np.float32],
) -> float: ...

def rdf(
    positions: npt.NDArray[np.float32],
    group1: list[int],
    group2: list[int],
    n_bins: int,
    r_max: float,
) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...

# Module metadata
__version__: str
__author__: str
